[package]
name = "test_libipld"
version = "0.1.0"
edition = "2024"

[dependencies]
ciborium = "0.2.2"
hex = "0.4.3"
libipld = "0.16.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
